from typing import Dict, List, Any, Optional

def call_external_api(tool_name: str) -> Dict[str, Any]:
    """
    Simulates fetching data from external API for OSRS Wiki search.

    Returns:
        Dict with simple scalar fields only (str, int, float, bool):
        - total_hits (int): Total number of matching pages found
        - continued (bool): Whether more results are available
        - offset (int): Current result offset for pagination
        - result_0_title (str): Title of first search result
        - result_0_pageid (int): Page ID of first search result
        - result_0_snippet (str): Snippet of first search result
        - result_0_titlesnippet (str): Title snippet of first search result
        - result_1_title (str): Title of second search result
        - result_1_pageid (int): Page ID of second search result
        - result_1_snippet (str): Snippet of second search result
        - result_1_titlesnippet (str): Title snippet of second search result
    """
    return {
        "total_hits": 42,
        "continued": True,
        "offset": 0,
        "result_0_title": "Dragon Scimitar",
        "result_0_pageid": 12345,
        "result_0_snippet": "A <span class='searchmatch'>dragon</span> scimitar is a powerful weapon...",
        "result_0_titlesnippet": "<span class='searchmatch'>Dragon</span> Scimitar",
        "result_1_title": "Dragon Sword",
        "result_1_pageid": 12346,
        "result_1_snippet": "The <span class='searchmatch'>dragon</span> sword is a two-handed sword...",
        "result_1_titlesnippet": "<span class='searchmatch'>Dragon</span> Sword"
    }

def old_school_runescape_wiki_and_data_server_osrs_wiki_search(
    search: str,
    limit: Optional[int] = 10,
    offset: Optional[int] = 0
) -> Dict[str, Any]:
    """
    Search the OSRS Wiki for pages matching a search term.

    Args:
        search (str): The term to search for on the OSRS Wiki (required)
        limit (int, optional): Number of results to return (1-50). Defaults to 10.
        offset (int, optional): Offset for pagination (0-based). Defaults to 0.

    Returns:
        Dict containing:
        - results (List[Dict]): List of search results with 'title', 'pageid', 'snippet', and 'titlesnippet'
        - total_hits (int): Total number of matching pages found
        - continued (bool): Whether more results are available beyond this response
        - offset (Optional[int]): Current result offset

    Raises:
        ValueError: If search is empty or limit is not between 1-50
    """
    if not search or not search.strip():
        raise ValueError("Search term is required and cannot be empty")
    
    if limit is not None and (limit < 1 or limit > 50):
        raise ValueError("Limit must be between 1 and 50")
    
    if limit is None:
        limit = 10
    
    # Call external API to get flattened data
    api_data = call_external_api("old-school-runescape-wiki-and-data-server-osrs_wiki_search")
    
    # Construct results list from indexed fields
    results = []
    
    # Process up to 2 results (as generated by call_external_api)
    for i in range(2):
        title_key = f"result_{i}_title"
        pageid_key = f"result_{i}_pageid"
        snippet_key = f"result_{i}_snippet"
        titlesnippet_key = f"result_{i}_titlesnippet"
        
        if title_key in api_data and api_data[title_key] is not None:
            results.append({
                "title": api_data[title_key],
                "pageid": api_data[pageid_key],
                "snippet": api_data[snippet_key],
                "titlesnippet": api_data[titlesnippet_key]
            })
    
    # Limit the number of results returned
    results = results[:limit]
    
    # Construct final response
    return {
        "results": results,
        "total_hits": api_data["total_hits"],
        "continued": api_data["continued"],
        "offset": api_data["offset"]
    }