from typing import Dict, List, Any, Optional

def call_external_api(tool_name: str) -> Dict[str, Any]:
    """
    Simulates fetching data from external API for Semantic Scholar paper details.
    
    Returns:
        Dict with simple fields only (str, int, float, bool):
        - paperId (str): unique identifier of the paper on Semantic Scholar
        - title (str): title of the academic paper
        - abstract (str): full abstract describing the paper's content and contributions
        - year (int): publication year of the paper
        - author_0_name (str): name of the first author
        - author_0_authorId (str): ID of the first author
        - author_1_name (str): name of the second author
        - author_1_authorId (str): ID of the second author
        - url (str): direct URL to the paper on Semantic Scholar
        - venue (str): publication venue such as journal or conference name
        - publicationTypes_0 (str): first type of publication
        - publicationTypes_1 (str): second type of publication
        - citationCount (int): total number of citations the paper has received
        - referenceCount (int): total number of references listed in the paper
        - influentialCitationCount (int): count of influential citations
        - fieldsOfStudy_0 (str): first academic field or discipline
        - fieldsOfStudy_1 (str): second academic field or discipline
        - publicationDate (str): full publication date in ISO format (YYYY-MM-DD)
        - tldr_model (str): model used to generate TL;DR summary
        - tldr_text (str): text of the short summary generated by Semantic Scholar
    """
    return {
        "paperId": "1234567890abcdef",
        "title": "A Study on Machine Learning Techniques in Academic Research",
        "abstract": "This paper explores the application of machine learning techniques in academic research, focusing on natural language processing and data mining methods.",
        "year": 2022,
        "author_0_name": "Alice Johnson",
        "author_0_authorId": "a1b2c3d4-e5f6-7890-g1h2-i3j4k5l6m7n8",
        "author_1_name": "Bob Smith",
        "author_1_authorId": "n8m7l6k5-j4i3-2109-h7g6-f5e4d3c2b1a0",
        "url": "https://www.semanticscholar.org/paper/1234567890abcdef",
        "venue": "Conference on Neural Information Processing Systems",
        "publicationTypes_0": "ConferencePaper",
        "publicationTypes_1": "Review",
        "citationCount": 150,
        "referenceCount": 45,
        "influentialCitationCount": 23,
        "fieldsOfStudy_0": "Computer Science",
        "fieldsOfStudy_1": "Artificial Intelligence",
        "publicationDate": "2022-12-05",
        "tldr_model": "semanticscholar-tldr-v1",
        "tldr_text": "Proposes novel ML approaches for analyzing academic literature with high accuracy."
    }

def semantic_scholar_academic_research_mcp_get_semantic_scholar_paper_details(paper_id: str) -> Dict[str, Any]:
    """
    Get details of a specific paper on Semantic Scholar.
    
    Args:
        paper_id (str): ID of the paper
        
    Returns:
        Dictionary containing paper details with the following structure:
        - paperId (str): unique identifier of the paper on Semantic Scholar
        - title (str): title of the academic paper
        - abstract (str): full abstract describing the paper's content and contributions
        - year (int): publication year of the paper
        - authors (List[Dict]): list of author objects, each containing 'name' (str) and 'authorId' (str) fields
        - url (str): direct URL to the paper on Semantic Scholar
        - venue (str): publication venue such as journal or conference name
        - publicationTypes (List[str]): types of publication (e.g., JournalArticle, ConferencePaper, Review)
        - citationCount (int): total number of citations the paper has received
        - referenceCount (int): total number of references listed in the paper
        - influentialCitationCount (int): count of influential citations that significantly impacted other research
        - fieldsOfStudy (List[str]): academic fields or disciplines the paper belongs to; null if unavailable
        - publicationDate (str): full publication date in ISO format (YYYY-MM-DD); null if unavailable
        - tldr (Dict): contains a short summary generated by Semantic Scholar with keys 'model' (str) and 'text' (str)
        
    Raises:
        ValueError: If paper_id is empty or None
    """
    if not paper_id:
        raise ValueError("paper_id is required and cannot be empty")
        
    # Call external API to get flattened data
    api_data = call_external_api("semantic-scholar-academic-research-mcp-get_semantic_scholar_paper_details")
    
    # Construct authors list from indexed fields
    authors = [
        {
            "name": api_data["author_0_name"],
            "authorId": api_data["author_0_authorId"]
        },
        {
            "name": api_data["author_1_name"],
            "authorId": api_data["author_1_authorId"]
        }
    ]
    
    # Construct publicationTypes list
    publication_types = [
        api_data["publicationTypes_0"],
        api_data["publicationTypes_1"]
    ]
    
    # Construct fieldsOfStudy list
    fields_of_study = [
        api_data["fieldsOfStudy_0"],
        api_data["fieldsOfStudy_1"]
    ]
    
    # Construct tldr object
    tldr = {
        "model": api_data["tldr_model"],
        "text": api_data["tldr_text"]
    }
    
    # Build final result matching output schema
    result = {
        "paperId": api_data["paperId"],
        "title": api_data["title"],
        "abstract": api_data["abstract"],
        "year": api_data["year"],
        "authors": authors,
        "url": api_data["url"],
        "venue": api_data["venue"],
        "publicationTypes": publication_types,
        "citationCount": api_data["citationCount"],
        "referenceCount": api_data["referenceCount"],
        "influentialCitationCount": api_data["influentialCitationCount"],
        "fieldsOfStudy": fields_of_study,
        "publicationDate": api_data["publicationDate"],
        "tldr": tldr
    }
    
    return result