from typing import Dict, List, Any, Optional

def call_external_api(tool_name: str) -> Dict[str, Any]:
    """
    Simulates fetching data from external API for Semantic Scholar paper match.

    Returns:
        Dict with simple fields only (str, int, float, bool):
        - matchScore (float): Score indicating how well the paper matches the query
        - paperId (str): Unique identifier for the paper on Semantic Scholar
        - title (str): Title of the matched paper
        - abstract (str): Summary of the paper's content; may be null
        - year (int): Publication year of the paper
        - author_0_name (str): Name of the first author
        - author_0_authorId (str): Author ID of the first author
        - author_1_name (str): Name of the second author
        - author_1_authorId (str): Author ID of the second author
        - url (str): URL to the paper's page on Semantic Scholar
        - venue (str): Publication venue (e.g., journal or conference name)
        - publicationTypes_0 (str): First publication type (e.g., "JournalArticle")
        - publicationTypes_1 (str): Second publication type (e.g., "Conference")
        - citationCount (int): Number of times the paper has been cited
        - tldr_model (str): Model used to generate TL;DR summary
        - tldr_text (str): AI-generated short summary of the paper; may be null
    """
    return {
        "matchScore": 0.95,
        "paperId": "123456789abcdef",
        "title": "Attention Is All You Need",
        "abstract": "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks...",
        "year": 2017,
        "author_0_name": "Ashish Vaswani",
        "author_0_authorId": "987654321fedcba",
        "author_1_name": "Noam Shazeer",
        "author_1_authorId": "876543210edcbaz",
        "url": "https://www.semanticscholar.org/paper/Attention-Is-All-You-Need-Vaswani-Shazeer/123456789abcdef",
        "venue": "NeurIPS",
        "publicationTypes_0": "Conference",
        "publicationTypes_1": "JournalArticle",
        "citationCount": 35000,
        "tldr_model": "semanticscholar-tldr-v1",
        "tldr_text": "We propose a new simple network architecture, the Transformer, based solely on attention mechanisms..."
    }

def semantic_scholar_academic_research_mcp_get_semantic_scholar_paper_match(query: str) -> Dict[str, Any]:
    """
    Find the best matching paper on Semantic Scholar using title-based search.

    Args:
        query (str): Paper title or partial title to match

    Returns:
        Dictionary containing the best matching paper with match score, including:
        - matchScore (float): score indicating how well the paper matches the query
        - paperId (str): unique identifier for the paper on Semantic Scholar
        - title (str): title of the matched paper
        - abstract (str): summary of the paper's content; may be null if not available
        - year (int): publication year of the paper
        - authors (List[Dict]): list of author objects, each with 'name' (str) and 'authorId' (str) fields
        - url (str): URL to the paper's page on Semantic Scholar
        - venue (str): publication venue (e.g., journal or conference name); may be empty
        - publicationTypes (List[str]): type(s) of publication, such as "JournalArticle", "Conference", or "Review"
        - citationCount (int): number of times the paper has been cited
        - tldr (Dict): contains a short summary generated by AI, with 'model' (str) and 'text' (str, may be null) fields

    Raises:
        ValueError: If query is empty or not a string
    """
    if not query or not isinstance(query, str):
        raise ValueError("Query must be a non-empty string")

    api_data = call_external_api("semantic-scholar-academic-research-mcp-get_semantic_scholar_paper_match")

    # Construct authors list from flattened fields
    authors = [
        {
            "name": api_data["author_0_name"],
            "authorId": api_data["author_0_authorId"]
        },
        {
            "name": api_data["author_1_name"],
            "authorId": api_data["author_1_authorId"]
        }
    ]

    # Construct publicationTypes list
    publication_types = [
        api_data["publicationTypes_0"],
        api_data["publicationTypes_1"]
    ]

    # Construct tldr object
    tldr = {
        "model": api_data["tldr_model"],
        "text": api_data["tldr_text"]
    }

    # Build final result structure matching output schema
    result = {
        "matchScore": api_data["matchScore"],
        "paperId": api_data["paperId"],
        "title": api_data["title"],
        "abstract": api_data["abstract"],
        "year": api_data["year"],
        "authors": authors,
        "url": api_data["url"],
        "venue": api_data["venue"],
        "publicationTypes": publication_types,
        "citationCount": api_data["citationCount"],
        "tldr": tldr
    }

    return result